books/urls.py
from django.conf.urls import url
from  .import views


urlpatterns=[
    url(r'^$',views.index,name='index'),
    #url(r'^search_form/$',views.search_form,name="search_form"),
    url(r'^search/$',views.search,name="search"),
    url(r'^contact/$',views.contact,name="contact"),

    #url(r'^current/$',views.current_url_view_good,name="current")
    url(r'^ua/$',views.ua_display_good1,name="ua")
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^zhangzihao/', admin.site.urls),
    url(r'^polls/',include('polls.urls',namespace='polls')),
    url(r'^books/',include('books.urls',namespace='books')),
]

books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    """一个模型对应于一个数据库表，
    模型中的各个属性分别对应于数据库表中的一列。
    属性的名称对应于列的名称，
    字段的类型（如CharField）对应于数据库列的类型（如 varchar）。"""
    name=models.CharField(max_length=30,verbose_name="名称")
    address=models.CharField(max_length=50,verbose_name="地址")  #自定义字段的标注
    city=models.CharField(max_length=60,verbose_name="城市")
    state_provice=models.CharField(max_length=60,verbose_name="省份")
    country=models.CharField(max_length=60,verbose_name="国家")
    website=models.URLField(verbose_name="网址")   #用于输入 URL 的 CharField。可选 max_length 选项

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "出版社"
        verbose_name_plural = "出版社"
        ordering=['name']  #按name排序

class Author(models.Model):
    first_name=models.CharField(max_length=30,verbose_name="姓氏")
    last_name=models.CharField(max_length=40,verbose_name="名字")
    email=models.EmailField(blank=True,verbose_name='邮箱地址')  #输入邮件地址的字段,设置blank=True允许该邮件字段为空,默认情况下blank=False
    class Meta:
        verbose_name="作者"
        verbose_name_plural="作者"
    def __str__(self):
        return u"%s %s" % (self.first_name,self.last_name)

class Book(models.Model):
    title=models.CharField(max_length=100,verbose_name="标题")
    authors=models.ManyToManyField(Author,verbose_name="作者")  #建立多对多关系
    publisher=models.ForeignKey(Publisher,verbose_name="出版社")  #建立一对多关系
    publication_date=models.DateField(blank=True,null=True,verbose_name="出版日期")   #出版时间  将时间设为可选字段
    class Meta:
        verbose_name="书籍"
        verbose_name_plural="书籍"
    def __str__(self):
        return self.title

books/forms.py
from django import forms

class ContactForm(forms.Form):  #建立表单
    subject=forms.CharField(min_length=10)    #括号可设置相关参数
    email=forms.EmailField(required=False,label="your email address")  #将email设为选填,其他默认必填
    message=forms.CharField(widget=forms.Textarea)  #widget设置表单表现逻辑

    def clean_message(self):   #Django 的表单系统会自动查找名称以 clean_ 开头、以字段名结尾的方法。
        message=self.cleaned_data['message']
        num_words=len(message.split())   #存储message的单词数
        if num_words<4:
            raise forms.ValidationError('Not enough words!')
        return message

books/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from books.models import Book
from books.forms import ContactForm
from django.core.mail import send_mail

# Create your views here.
def index(request):
    return  HttpResponse('Hello, books.')

# def search_form(request):
#     return render(request,'search_form.html')

#def search(request):
    # if 'q' in request.GET and request.GET['q']:   #检查 request.GET 中有没有 'q' ,request.GET['q'] 是不是空值，
    #   q=request.GET['q']
    #   books=Book.objects.filter(title__icontains=q)    #在图书表中查找所有书名中包含查询词条的书
    #   return render(request,'search_results.html',{'books':books,'query':q})  #字典中的值替换模板变量
    # else:
    #     return render(request,'search_form.html',{'error':True})

    # errors=[]   #空列表也表示为false
    # if 'q' in request.GET:  #任何输入的字符都能接受,包括空值
    #     q=request.GET['q']
    #     if not q:
    #         errors.append('Enter a search term.')
    #     elif len(q)>20:  #验证输入的字符串是否超过20个,若超过需重新输入
    #         errors.append('Please enter at most 20 characters.')
    #     else:
    #         books=Book.objects.filter(title__icontains=q)
    #         return render(request,'search_results.html',{'books':books,'query':q})
    #     return render(request,'search_form.html',{'errors':errors})

def search(request):
    errors=[]
    if 'q' in request.GET:  #包括空值
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q)>20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'search_results.html',{'books': books, 'query': q})
    return render(request,"search_form.html",{'errors':errors})

def contact(request):
    if request.method=='POST':  #判断请求方法是否为post
        form=ContactForm(request.POST)  #将想要发送的请求传到变量form中
        if form.is_valid():
            cd=form.cleaned_data   #清理数据,返回字符串对象
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email','zhangzihao@163.com'),['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form=ContactForm(initial={'subject':'I love your site!','message':'It is very beautiful'})  #如果不是post请求,就创建一个空表单,initial参数设置初始值
    return  render(request,'contact_form.html',{'form':form})


#HttpRequest 对象的方法和属性
# def current_url_view_good(request):
#     return HttpResponse("Welcome to the page at %s" % request.get_host())

#request.META 的值是一个 Python 字典，包含请求的所有 HTTP 首部，例如用户的 IP 地址和用户代理（user agent，通常是 Web 浏览器的名称和版本）。
def ua_display_good1(request):
    try:
        ua = request.META['REMOTE_ADDR']
    except KeyError:
        ua = 'unknown'
    return HttpResponse("Your browser is %s" % ua)

books/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>

</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">  {# action作用是实现网页跳转 #}
{#        <div class="field">       {# 自定义表单外观 #}
{#            {{ form.subject.errors }}#}
{#            <label for="id_subject">Subject:</label>#}
{#            {{ form.subject }}#}
{#        </div>#}
{#        <div class="field">#}
{#            {{ form.email.errors }}#}
{#            <label for="id_email">Your e-mail address:</label>#}
{#            {{ form.email }}#}
{#        </div>#}
{#        <div class="field">#}
{#            {{ form.message.errors }}#}
{#            <label for="id_message">Message:</label>#}
{#            {{ form.message }}#}
{#        </div>#}
        <table>
              {{ form.as_table }}    {# 显示表单#}
        </table>
        {% csrf_token %}  {#防止跨站请求伪造#}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

books/templates/search_form.html
{#<html>#}
{#<head>#}
{#    <title>Search</title>  {# 网页标题 #}
{#</head>#}
{#<body>#}
{#        {% if errors %}#}
{#            <ul>#}
{#                {% for error in errors %}#}
{#                 <li>{{ error }}</li>  {#输出errors列表中的元素#}
{#                {% endfor %}#}
{#            </ul>#}
{#        {% endif %}#}
{#        <form action="search_results" method="get">  {#提交之后跳转到相应网页,此时还是原来网页#}
{#            <input type="text" name="q">         {#添加文本框#}
{#            <input type="submit" value="Search">  {#添加提交按钮  名叫Search#}
{#        </form>#}
{#</body>#}
{#</html>#}

<html>
<head>
    <title>Search</title>
</head>
<body>
    {% if errors %}
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
    {% endif %}
    <form action=""  method="get">   {# ???这里网页跳转有问题 #}
        <input type="text" name="q">
        <input type="submit" value="提交">
    </form>
</body>
</html>

books/templates/search_results.html
<html>
    <head>
        <title>Book Search</title>
    </head>
    <body>
        <p>You searched for:<strong>{{ query }}</strong></p>
        {% if books %}
            <p>Found {{ books|length }} book{{ books|pluralize }}</p>  {#pluralize 模板过滤器，它会根据找到的图书数量输出正确的单复数#}
            <u>
                {% for book in books %}
                    <li>{{ book.title }}</li>
                {% endfor %}
            </u>
        {% else %}
            <p>No books matched your search criteria.</p>
        {% endif %}
    </body>
</html>